library/urls.py
from django.conf.urls import patterns, include, url
import library.views
import users.views
from django.views.static import * 
from django.conf import settings

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^$', 'library.views.home'),
    url(r'^login/$', 'users.views.login'),
    url(r'^logout/$', 'library.views.logout'),
    url(r'^register/$', 'users.views.register'),
    url(r'^dashboard/$', 'users.views.dashboard'),
    url(r'^addBook/$', 'books.views.addBook'),
    url(r'^addAuthor/$', 'books.views.addAuthor'),
    url(r'^addPublisher/$', 'books.views.addPublisher'),
    
    # url(r'^library/', include('library.foo.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

books/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from users.models import User

# Create your models here.
class Publisher(models.Model):
	name = models.CharField(max_length=30, unique=True)
	website = models.CharField(max_length=200)
	email = models.EmailField(max_length=75, unique=True)
	city = models.CharField(max_length=25)

	def __unicode__(self):
		return self.name

class Author(models.Model):
	name = models.CharField(max_length=30, unique=True)
	email = models.EmailField(max_length=50)
	phone = models.CharField(max_length=10, unique=True, validators=[RegexValidator(regex='^\d{10}$', message='Length has to be 10', code='Invalid number')])

	def __unicode__(self):
		return self.name

class Book(models.Model):
	title = models.CharField(max_length=50, unique=True)
	authors = models.ManyToManyField(Author)
	publisher = models.ForeignKey(Publisher)
	added_user = models.ForeignKey(User)
	publication_date = models.DateField()

	def __unicode__(self):
		return self.title

books/forms.py
import datetime
from django import forms
from django.core.validators import RegexValidator, URLValidator, EmailValidator, validate_email
from books.models import *
from django.contrib.admin import widgets

class AddAuthorForm(forms.Form):
	name = forms.CharField(max_length=30)
	email = forms.EmailField()
	phone = forms.IntegerField(validators=[RegexValidator(regex='^\d{10}$', message='Length has to be 10', code='Invalid number')])

class AddPublisherForm(forms.Form):
	name = forms.CharField(max_length=30)
	website = forms.CharField(max_length=200, validators=[URLValidator()])
	email = forms.CharField(max_length=75, validators=[validate_email])
	city = forms.CharField(max_length=25, validators=[RegexValidator(regex='^[a-zA-Z\h]+$', message='Should be characters(space allowed)', code='Invalid city name')])

class AddBookForm(forms.Form):
	title = forms.CharField(max_length=50)
	authors = forms.ModelMultipleChoiceField(queryset=Author.objects.all())
	publisher = forms.ModelChoiceField(queryset=Publisher.objects.all(), initial=Publisher.objects.get() if Publisher.objects.count() > 0 else None)
	publication_date = forms.DateField()
	# def __init__(self, *args, **kwargs):
	# 	super(AddBookForm, self).__init__(*args, **kwargs)
	# 	self.fields['publication_date'].widget = widgets.AdminDateWidget()

books/views.py
from django.shortcuts import render
from books.forms import *
from users.models import User
from books.models import *
from hashlib import sha1
from django.http import HttpResponseRedirect

# Create your views here.
def addAuthor(request):
	d = {'title': 'Library :: Add Author'}
	if 'user' in request.session:
		d['name'] = request.session['user'].name
	else:
		return HttpResponseRedirect('/login/')
	form = AddAuthorForm(request.POST or None)
	d['form'] = form
	if form.is_valid():
		data = form.cleaned_data
		author = Author(name=data['name'], email=data['email'], phone=data['phone'])
		author.save()
		return HttpResponseRedirect('/dashboard/')
	return render(request, 'add_author.html', d)

def addPublisher(request):
	d = {'title':'Library :: Add Publisher'}
	if 'user' in request.session:
		d['name'] = request.session['user'].name
	else:
		return HttpResponseRedirect('/login/')
	
	form = AddPublisherForm(request.POST or None)
	if form.is_valid():
		data = form.cleaned_data
		publisher = Publisher(name=data['name'], website=data['website'], 
			email=data['email'], city=data['city'])
		publisher.save()
		return HttpResponseRedirect('/dashboard/')
	d['form'] = form
	return render(request, 'add_publisher.html', d)

def addBook(request):
	d = {'title':'Library :: Add Book'}
	if 'user' in request.session:
		d['name'] = request.session['user'].name
	else:
		return HttpResponseRedirect('/login/')
	form = AddBookForm(request.POST or None)
	if form.is_valid():
		data = form.cleaned_data
		book = Book(title=data['title'],  
			publisher=data['publisher'], publication_date=data['publication_date'], 
			added_user=User.objects.get(username=request.session['user'].username))
		book.save()
		book.authors.add(*data['authors'])
		book.save()
		return HttpResponseRedirect('/dashboard/')
	d['form'] = form
	return render(request, 'add_book.html', d)

books/templates/add_author.html
<html>
	<head>
		<title> {{ title }} </title>
		<link rel="stylesheet" type="text/css" href="/media/books.css">
	</head>
	<body>
		<ul id="header">
			<li><a href="/"><input type="button" value="Home" /></a> </li>
			<li><a href="/dashboard/"><input type="button" value="Dashboard" /></a> </li>
			<li>Welcome {{ name }}, </li>
		</ul>
		
		<form action="/addAuthor/" method="post" id="addBookForm">
			<table>
				{{ form.as_table }}
			</table>
			<input type="submit" value="Submit">
			{% csrf_token %}
		</form>

	</body>
</html>

books/templates/add_book.html
<html>
	<head>
		<title> {{ title }} </title>
		{{ form.media }}
		
		<link rel="stylesheet" href="/media/css/jquery.ui.core.css">
		<link rel="stylesheet" href="/media/css/jquery.ui.datepicker.css">
		<link rel="stylesheet" href="/media/css/jquery.ui.theme.css">

		<link rel="stylesheet" type="text/css" href="/media/books.css">

		<script src="/media/js/jquery-1.9.1.js"></script>
		<script src="/media/js/jquery.ui.core.js"></script>
		<script src="/media/js/jquery.ui.widget.js"></script>
		<script src="/media/js/jquery.ui.datepicker.js"></script>
		<script>
		$(function() {
			$( "#id_publication_date" ).datepicker();
		});
		</script>
	</head>
	<body>
		<ul id="header">
			<li><a href="/"><input type="button" value="Home" /></a> </li>
			<li><a href="/dashboard/"><input type="button" value="Dashboard" /></a> </li>
			<li>Welcome {{ name }}, </li>
		</ul>
		
		<form action="/addBook/" method="post" id="addBookForm">
			<table>
				{{ form.as_table }}
			</table>
			<input type="submit" value="Submit">
			{% csrf_token %}
		</form>

	</body>
</html>

books/templates/add_publisher.html
<html>
	<head>
		<title> {{ title }} </title>
		<link rel="stylesheet" type="text/css" href="/media/books.css">
	</head>
	<body>
		<ul id="header">
			<li><a href="/"><input type="button" value="Home" /></a> </li>
			<li><a href="/dashboard/"><input type="button" value="Dashboard" /></a> </li>
			<li>Welcome {{ name }}, </li>
		</ul>
		
		<form action="/addPublisher/" method="post" id="addBookForm">
			<table>
				{{ form.as_table }}
			</table>
			<input type="submit" value="Submit">
			{% csrf_token %}
		</form>

	</body>
</html>